version: "3"
services:
    mysqldbm:
        image: 'mysql:8'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=employee_management_system
        ports:
            - "3344:3306"
    springboot-docker-containern:
        image: springboot-docker-containern
        ports:
            - "8025:8080"
        environment: 
            SPRING_DATASOURCE_URL: jdbc:mysql://mysqldbm:3306/employee_management_system
            SPRING_DATASOURCE_USERNAME: "root"
            SPRING_DATASOURCE_PASSWORD: "root"
        build:
            context: "./"
            dockerfile: "Dockerfile"
        depends_on:
            - mysqldbm
