version: "3"
services:
    mysqldb3:
        image: 'mysql:8'
        command: mysqld --general-log=1 --general-log-file=/var/log/mysql/general-log.log
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=employee_management_system
        ports:
            - "3345:3306"
        healthcheck:
          test: "cat /var/log/mysql/general-log.log | grep \"root@localhost on  using Socket\""
          interval: 1s
          retries: 120
    springboot-docker-container3:
        image: springboot-docker-container3
        ports:
            - "8026:8080"
        environment: 
            SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb3:3306/employee_management_system
            SPRING_DATASOURCE_USERNAME: "root"
            SPRING_DATASOURCE_PASSWORD: "root"
        build:
            context: "./"
            dockerfile: "Dockerfile"
        depends_on:
        mysql:
            condition: service_healthy
